[project]
name = "pytest-autouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
dev-dependencies = [
    "anyio>=4.6.0",
    "pytest>=8.3.3",
]
